[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
        max-age=63072000;
        includeSubDomains;
        preload'''
[build]
    base = "/"
    command = "swift build -c release --disable-sandbox --enable-test-discovery" 
    publish = "./.build/release/App
    
